# This is a basic workflow to help you get started with Actions

name: Create-Issue

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Create-Issue:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: REST API create issue
        run: |
          notification_text=":ibm-warning-filled: some alert message"
          if curl -X POST \
                  -H 'Content-type: application/json' \
                  -d '{"text":"'"$notification_text"'"}' \
                  ${{ secrets.SLACK_INCOMING_WEBHOOK }}; then
              echo "Slack message successfully created"
          else
              echo "Slack message creation failed"
              exit 1
          fi
