# This is a basic workflow to help you get started with Actions

name: Create-Issue

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Create-Issue:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: REST API create issue
        run: |
          if curl -sL --fail\
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -d '{"title":"Test 6",\
                  "body":"For details see: https://github.com/${{ github.repository }}//actions/runs/${{ github.run_id }}/job/${{ github.job }}",\
                  "labels":["bug"]}'; then
              echo "Issue successfully created"
          else
              echo "Issue creation failed"
              exit 1
          fi
