# This is a basic workflow to help you get started with Actions

name: Create-Issue

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

jobs:
  Create-Issue:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create Issue on Failed workflow
        run: |
          response=$(curl -sL \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -d '{"title":"Release Pipeline failed","body":"For details see: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","labels":["bug"]}')
          url=$(echo "$response" | jq -r '.url')
          if [ ! -z "$url" ]; then
              echo "Issue successfully created"
              notification_text=":ibm-warning-filled: Release Pipeline failed. For details see: $url."
              if curl -s -X POST \
                      -H 'Content-type: application/json' \
                      -d '{"text":"'"$notification_text"'"}' \
                      ${{ secrets.SLACK_INCOMING_WEBHOOK }} \
                      -o /dev/null; then
                  echo "Slack message successfully created"
              else
                  echo "Slack message creation failed"
              fi
          else
              echo "Issue creation failed"
          fi
