
name: Fail

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Fail:
    runs-on: ubuntu-latest

    steps:
      - name: Fail
        run: |
          exit 1

  create-failure-notifications:
      needs: [ Fail ]
      uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/create-gh-issue-and-slack-message.yml@gha-pipeline-fail-alert
      secrets: inherit
      if: ${{ failure() }}